### ISSUE TITLE
consider fxn for working with ASCII files

### ISSUE THREAD

**Issue by fsolt** [fsolt/ropercenter#4]
cf. [readroper](https://github.com/petulla/readroper) (which doesn't seem to work on the surveys I've tried)

**Comment by petulla** [comment]
hey -- readroper maintainer here. do you mind pointing me to the surveys it didn't work on? We've been using it here on 70s/80s surveys successfully but no doubt it needs more battle testing.

**Comment by fsolt** [comment]
Here's one that I couldn't get to work: [USAIPOGNS1992-222054](https://ropercenter.cornell.edu/CFIDE/cf/action/catalog/abstract.cfm?type=&start=&id=&archno=USAIPOGNS1992-222054&abstract=).  

Anyway, would you mind taking a look at the [read_ascii()](https://github.com/fsolt/ropercenter/blob/master/R/read_ascii.R) fxn I wrote up y'day?  I nearly wrote it up first as a PR to you, but ended up just putting it here to start.  I'll still submit the PR if you're interested, then I can import it back to ropercenter.

**Comment by petulla** [comment]
sure, submitting the pr sounds good. ill test from there. thanks.

**Comment by petulla** [comment]
I see the issue on my implementation, am fixing. I've sent the latest to CRAN, should be fixed in 24-48, was just a parens in the wrong place :/
