### ISSUE TITLE
Conversion from .por to .RData failed

### ISSUE THREAD

**Issue by mikedecr** [fsolt/ropercenter#5]
Hi, this package has been a great help on my dissertation work.

I want to bring an issue with por -> Rdata conversion to your attention. I've noticed suddenly that conversion is just failing and I can't explain why. 

If I prevent `roper_download()` from trying to convert the por file and instead try to read it directly into R using `haven::read_por`, I get error message "Failed to parse [file].por: Invalid file, or file has unsupported features." Traceback suggests there is an issue with `df_parse_por_file()` but I actually can't find where that function lives. 

This likely is an issue with `haven` or something even farther up in the pipeline (others are running into similar issues and reporting them to `haven` [here](https://github.com/tidyverse/haven/issues/412)), but I wanted to bring it to your attention since this might be A Thing.

**Comment by zross** [comment]
I see you referenced the issue I raised (#412) and I can definitely see them related. Were your SPSS `por` files created from SPSS version 25? Do you have a `por` file created from an earlier version of SPSS you could test?

**Comment by mikedecr** [comment]
@zross Unfortunately I have no clue. The `.por` files are being pulled from an online API, so I don't know how I would check which version those files were generated by. Is there a way to learn which version generated a `.por` file using the file itself? (n.b. I don't have access to an SPSS license)

**Comment by mikedecr** [comment]
Oh wait! I see that [a fix](https://github.com/WizardMac/ReadStat/issues/157) is en route on the (edit) ReadStat side of things. Will close this and reopen if the issue persists.
